### ISSUE TITLE
Issue for Python 3.9

### ISSUE THREAD

**Issue by Jinsong-Zhou** [corentin-ryr/MultiMedEval#45]
Traceback (most recent call last):
  File "/hpc2hdd/home/jzhou945/Developer/Dataset/setup.py", line 1, in <module>
    from multimedeval import MultiMedEval, SetupParams, EvalParams
  File "/hpc2hdd/home/jzhou945/miniconda3/envs/medeval/lib/python3.9/site-packages/multimedeval/__init__.py", line 2, in <module>
    from multimedeval.utils import EvalParams, SetupParams
  File "/hpc2hdd/home/jzhou945/miniconda3/envs/medeval/lib/python3.9/site-packages/multimedeval/utils.py", line 96, in <module>
    class SetupParams:
  File "/hpc2hdd/home/jzhou945/miniconda3/envs/medeval/lib/python3.9/site-packages/multimedeval/utils.py", line 129, in SetupParams
    MedQA_dir: Optional[str|os.PathLike] = None
TypeError: unsupported operand type(s) for |: 'type' and 'ABCMeta'

**Comment by corentin-ryr** [comment]
Hi @Jinsong-Zhou ,

Thank you for reporting this issue and for using MultiMedEval.

We’re aware of this problem, and I’m happy to let you know that it has already been addressed. The fix will be included in the next release of MultiMedEval.

In the meantime, if you’d like to use the latest version, you can install it directly from GitHub using pip. Please note that this version includes breaking changes compared to version 0.1.1, so some adjustments may be necessary.

Feel free to reach out if you have any further questions or need assistance!
